route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            username: 'Lars Tufvesson'
            channel: '#devops'
            api_url: 'https://hooks.slack.com/services/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'
