route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            username: 'lars.tufvesson'
            channel: '#devops'
            api_url: 'https://hooks.slack.com/services/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'
